[package]
name = "sealed-ch"
version = "0.0.1"
edition = "2018"

[dependencies]
rocket = "0.4.10"
rocket_cors = "0.5.2"
image = "0.23.14"
serde_json = "1.0"
zip = "0.5.13"
qrcode = "0.12.0"
rocket-multipart-form-data = "0.9.0-rc.1"
fnv = "1.0.7"

[[bin]]
name = "sealed-ch"
path = "src/main.rs"